### ISSUE TITLE
Niepoprawne wyszukiwanie bicia przez damki

### ISSUE THREAD

**Issue by psrok1** [psrok1/RussianCheckers#2]
Po przesunięciu pionka i zamiany w damkę - metoda Piece.move() zgłasza, że istnieje kolejne bicie zawsze, gdy obok znajdzie się pionek innego koloru. Zgłasza nawet wtedy, gdy bicie jest niemożliwe (np. za pionkiem znajduje się kolejny pion).
Metoda getPossibilities() zwraca wtedy poprawny (pusty) rezultat, co skutkuje zablokowaniem gry.

Problem prawdopodobnie leży w Piece.kingChange.
Wykonuje ona sprawdzenie jedynie przy pomocy findToJump, nie sprawdzając czy znaleziony pion można w ogóle przeskoczyć.

**Comment by pietrzykp** [comment]
Teraz powinno byc ok.

**Comment by psrok1** [comment]
Ok, wszystko działa :)
